export const FETCHING_SERVERS = 'FETCHING_SERVERS';
export const DONE_FETCHING_SERVERS = 'DONE_FETCHING_SERVERS';
export const ADD_SERVER = 'ADD_SERVER';
export const UPDATE_SERVER = 'UPDATE_SERVER';
export const REMOVE_SERVER = 'REMOVE_SERVER';

export const FETCHING_STREAMS = 'FETCHING_STREAMS';
export const DONE_FETCHING_STREAMS = 'DONE_FETCHING_STREAMS';
export const ADD_STREAM = 'ADD_STREAM';
export const UPDATE_STREAM = 'UPDATE_STREAM';
export const REMOVE_STREAM = 'REMOVE_STREAM';

export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const LOAD_SETTINGS = 'LOAD_SETTINGS';
